package main.java.ownClasses.presentation;

import ownClasses.domain.domainControllers.DomainPersistanceController;

import javax.swing.*;
import java.awt.*;

/**
 * Created by iansangines on 01/06/2016.
 */
public class PresentationEditNode extends JFrame {
    private JTextField textField1;
    private JTextField textField2;
    private JButton acceptarButton;
    private JButton cancelarButton;
    private DomainPersistanceController persistanceController;

    public PresentationEditNode(DomainPersistanceController persistanceController, int selectedIndex) {
        this.persistanceController = persistanceController;

        switch (selectedIndex) {
            case (0):
                break;
            case (1):
                break;
            case (2):
                break;
            case (3):
                break;
        }

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Nom:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipady = 20;
        gbc.insets = new Insets(0, 10, 0, 0);
        panel1.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Nom nou:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipady = 20;
        gbc.insets = new Insets(0, 10, 0, 0);
        panel1.add(label2, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 350;
        gbc.ipady = 6;
        gbc.insets = new Insets(0, 0, 3, 0);
        panel1.add(textField1, gbc);
        textField2 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipady = 6;
        gbc.insets = new Insets(3, 0, 0, 0);
        panel1.add(textField2, gbc);
        cancelarButton = new JButton();
        cancelarButton.setText("Cancelar");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 40;
        gbc.ipady = 6;
        gbc.insets = new Insets(50, 20, 10, 20);
        panel1.add(cancelarButton, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Edit Node");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 130, 0, 0);
        panel1.add(label3, gbc);
        acceptarButton = new JButton();
        acceptarButton.setMaximumSize(new Dimension(36, 32));
        acceptarButton.setMinimumSize(new Dimension(36, 32));
        acceptarButton.setPreferredSize(new Dimension(36, 32));
        acceptarButton.setText("Acceptar");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 200;
        gbc.insets = new Insets(50, 10, 10, 0);
        panel1.add(acceptarButton, gbc);
    }
}
