package main.java.ownClasses.presentation;

import main.java.sharedClasses.domain.domainControllers.DomainPersistanceController;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;

/**
 * Created by iansangines on 10/05/2016.
 */
public class PresentationEditGraph extends JFrame {
    private JButton editNodeButton;
    private JButton deleteNodeButton;
    private JButton addNodeButton;
    private JPanel buttons;
    private JList editList;
    private JList addList;
    private JList deleteList;
    private JPanel panel;

    public DomainPersistanceController persistanceController;

    public PresentationEditGraph(DomainPersistanceController persistanceController) {
        super("EDIT GRAPH");

        this.persistanceController = persistanceController;
        setContentPane(panel);
        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        editNodeButton.addActionListener(e -> editNodeAction("edit"));
        deleteNodeButton.addActionListener(e -> editNodeAction("delete"));
        addNodeButton.addActionListener(e -> editNodeAction("add"));
        setVisible(true);
    }

    private void editNodeAction(String action) {
        System.out.println("EditNodeAction");
        if (action.equals("edit")) {
            editList.setVisible(true);
            editList.addListSelectionListener(listListener);
        } else if (action.equals("delete")) {
            deleteList.setVisible(true);
            deleteList.addListSelectionListener(listListener);
        } else if (action.equals("add")) {
            addList.setVisible(true);
            addList.addListSelectionListener(listListener);
        }
    }

    ListSelectionListener listListener = new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (e.getSource() == editList) {
                String selected = editList.getSelectedValue().toString();
                //persistanceController.editNode(selected);
            } else if (e.getSource() == deleteList) {

            } else if (e.getSource() == addList) {

            }
        }
    };

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(30, 30, 30, 30), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Edit Grap");
        panel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttons = new JPanel();
        buttons.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(buttons, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        editNodeButton = new JButton();
        editNodeButton.setText("Edit Node");
        buttons.add(editNodeButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteNodeButton = new JButton();
        deleteNodeButton.setText("Delete Node");
        buttons.add(deleteNodeButton, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        addNodeButton = new JButton();
        addNodeButton.setText("Add Node");
        buttons.add(addNodeButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        editList = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("Author");
        defaultListModel1.addElement("Paper");
        defaultListModel1.addElement("Term");
        defaultListModel1.addElement("Conference");
        editList.setModel(defaultListModel1);
        editList.setVisible(false);
        buttons.add(editList, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        addList = new JList();
        final DefaultListModel defaultListModel2 = new DefaultListModel();
        defaultListModel2.addElement("Author");
        defaultListModel2.addElement("Paper");
        defaultListModel2.addElement("Term");
        defaultListModel2.addElement("Conference");
        addList.setModel(defaultListModel2);
        addList.setVisible(false);
        buttons.add(addList, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        deleteList = new JList();
        deleteList.setInheritsPopupMenu(false);
        final DefaultListModel defaultListModel3 = new DefaultListModel();
        defaultListModel3.addElement("Author");
        defaultListModel3.addElement("Paper");
        defaultListModel3.addElement("Term");
        defaultListModel3.addElement("Conference");
        deleteList.setModel(defaultListModel3);
        deleteList.setVisible(false);
        buttons.add(deleteList, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
