package main.java.ownClasses.presentation;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 * Created by Nicola on 16/05/2016.
 */
public class PresentationResult extends JFrame {
    private JTextArea textArea1;
    private JPanel panel;

    public PresentationResult(ArrayList<String> resultat) {
        super("RESULTAT");

        setContentPane(panel);
        pack();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        for (int i = 0; i < resultat.size(); i++)
            textArea1.append("\n" + (i + 1) + ". " + resultat.get(i));

        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("NOM  -> RELEVANCE");
        panel.add(label1);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1);
        textArea1 = new JTextArea();
        scrollPane1.setViewportView(textArea1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
