package main.java.ownClasses.presentation;

import javax.swing.*;
import java.awt.*;

/**
 * Created by iansangines on 01/06/2016.
 */
public class PresentationdeleteNode {
    private JTextField textField1;
    private JButton acceptarButton;
    private JButton cancelarButton;
    private JLabel Nom;
    private JLabel DeleteNode;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        Nom = new JLabel();
        Nom.setText("Nom:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipady = 150;
        gbc.insets = new Insets(0, 20, 0, 0);
        panel1.add(Nom, gbc);
        textField1 = new JTextField();
        textField1.setMargin(new Insets(3, 10, 3, 40));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 350;
        gbc.ipady = 5;
        gbc.insets = new Insets(0, 10, 0, 0);
        panel1.add(textField1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer2, gbc);
        DeleteNode = new JLabel();
        DeleteNode.setText("Delete Node");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.insets = new Insets(0, 100, 0, 0);
        panel1.add(DeleteNode, gbc);
        cancelarButton = new JButton();
        cancelarButton.setText("Cancelar");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipady = 6;
        gbc.insets = new Insets(0, 0, 20, 10);
        panel1.add(cancelarButton, gbc);
        acceptarButton = new JButton();
        acceptarButton.setMaximumSize(new Dimension(66, 32));
        acceptarButton.setMinimumSize(new Dimension(66, 32));
        acceptarButton.setOpaque(false);
        acceptarButton.setPreferredSize(new Dimension(66, 32));
        acceptarButton.setText("Acceptar");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 250, 20, 10);
        panel1.add(acceptarButton, gbc);
    }
}
